services:
  # 1. Database
  db:
    image: postgres:latest
    container_name: ergo_db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ergouser
      POSTGRES_PASSWORD: ergopassword
      POSTGRES_DB: ergodb
    volumes:
      - ./pgdata:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Uncomment to auto-run a setup script
    ports:
      - "5432:5432" # Expose for local development/management tools like DBeaver
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ergouser -d ergodb -h localhost"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  # 2. Backend API & Hardware Controller
  api:
    build: ./api
    container_name: ergo_api
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://ergouser:ergopassword@db:5432/ergodb
      - ERGOMETERS_CONFIG={"Ergo1":"192.168.1.50:25000", "Ergo2":"192.168.1.51:25000"}
    depends_on:
      - db
    ports:
      - "8000:8000"
    healthcheck:
      test: curl --fail http://localhost:8000/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    
    # --- HARDWARE ACCESS UNCOMMENT AS NEEDED ---
    # If connecting via USB/Serial cable (Linux):
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    
    # If connecting via Bluetooth/BLE (Linux):
    # network_mode: "host" 
    # volumes:
    #   - /var/run/dbus/:/var/run/dbus/:z

  # 3. Web Server (Frontend UI)
  web:
    image: zauberzeug/nicegui:latest
    restart: always
    ports:
        - 80:8080
    volumes:
        - ./web/:/app/
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8080/', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s